
# Migarate, within Django Models (11 Django Models) of Django Tutorial Section
# After running initial migration command python manage.py makemigrations members,
# Django automatically creates this file in migrations folder, 
# that describes initial changes from first migration.


# Generated by Django 4.2.1 on 2023-05-27 01:48


# comment code for now     
from django.db import migrations, models


# comment code for now     
class Migration(migrations.Migration):

    # comment code for now    
    initial = True

    # comment code for now    
    dependencies = [
    # comment code for now    
    ]

    # comment code for now    
    operations = [
        # comment code for now    
        migrations.CreateModel(
            # comment code for now    
            name='Member',
            # comment code for now    
            fields=[
                # comment code for now    
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # comment code for now    
                ('firstname', models.CharField(max_length=255)),
                # comment code for now    
                ('lastname', models.CharField(max_length=255)),
            # comment code for now    
            ],
        # comment code for now    
        ),
    # comment code for now    
    ]