
# Migarate, within Django Models (9 Django URLs) of Django Tutorial Section
# After running initial migration command python manage.py makemigrations members,
# Django automatically creates this file in migrations folder, 
# that describes initial changes from first migration.


# Generated by Django 4.2.1 on 2023-05-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
    ]
    
    
    
