# Generated by Django 4.2.1 on 2023-05-28 12:09

# Note: This Migration File 0002_member_joined_date_member_phone.py was created in Add Fields in the Model, 
# within Django Update Model (15 Django Update Model) of Django Tutorial Section 
# This Migration File adds 2 fields (joined_date and phone) to models.py
# and was created with a migration using python manage.py makemigrations members to update database.   


# comment code for now    
from django.db import migrations, models


# comment code for now    
class Migration(migrations.Migration):

    # comment code for now    
    dependencies = [
        # comment code for now    
        ('members', '0001_initial'),
    # comment code for now    
    ]

    # comment code for now    
    operations = [
        # comment code for now    
        migrations.AddField(
            # comment code for now    
            model_name='member',
            # comment code for now    
            name='joined_date',
            # comment code for now    
            field=models.DateField(null=True),
        # comment code for now    
        ),
        # comment code for now    
        migrations.AddField(
            # comment code for now    
            model_name='member',
            # comment code for now    
            name='phone',
            # comment code for now    
            field=models.IntegerField(null=True),
        # comment code for now    
        ),
    # comment code for now    
    ]
